const BACKEND_WEBSERVER_HOST = "http://localhost:10083";
const BACKEND_WS_HOST = BACKEND_WEBSERVER_HOST;

const REDIRECT_TIME = 2000;
const RESEND_EMAIL_TIME = 30;

export {
  BACKEND_WEBSERVER_HOST,
  BACKEND_WS_HOST,
  REDIRECT_TIME,
  RESEND_EMAIL_TIME,
};
