// const BACKEND_WEBSERVER_HOST = "http://localhost:10083";
// const BACKEND_WS_HOST = "http://localhost:10083";
const BACKEND_WEBSERVER_HOST = "http://52.76.77.52:8001";
const BACKEND_WS_HOST = BACKEND_WEBSERVER_HOST;

const REDIRECT_TIME = 3000;
const RESEND_EMAIL_TIME = 30;

export {
  BACKEND_WEBSERVER_HOST,
  BACKEND_WS_HOST,
  REDIRECT_TIME,
  RESEND_EMAIL_TIME,
};
